### ISSUE TITLE
RespReader.js class BulkString tries to call toString() on null object

### ISSUE THREAD

**Issue by cinnay** [gorankarlic/ok-redis#4]
RespReader.js class BulkString under some circumstances tries to call toString() on this.r = null.

```
class BulkString extends Bulk
{
    ...
    result()
    {
        return this.r.toString();
    }
}
```

`return this.r ? this.r.toString() : null;` does the job.

**Comment by gorankarlic** [comment]
Thanks. Fixed with `return this.r === null ? null : this.r.toString()` (cleaner code avoiding falsy conditionals).

**Comment by cinnay** [comment]
thanks ;)
