### ISSUE TITLE
"const client = await Redis.connect(opts);" not working as intended.

### ISSUE THREAD

**Issue by cinnay** [gorankarlic/ok-redis#6]
In case of using
`const client = await Redis.connect(opts);`
RedisClient.connect will return a Promise to the Redis.connect function which ignores the promise and just proceeds to return the client instead of a promise that would return the client. Thous any error that occurs during the connect will throw an UnhandlePromisRejectionWarning and keeps the app dangling.
```
class Redis
{
    ...
    static connect(opts = new RedisOpts(), done = void null)
    {
        const client = new RedisClient(opts.opts);
        client.connect(done); 
        return client;
    }
    ...
}

class RedisClient extends Commands
{
    ...
    connect(done)
    {
        if(done === void null)
        {
            return new Promise((resolve, reject) => this._client.connect((err, result) => err === null ? resolve(result) : reject(err)));
        }
        else
        {
            this._client.connect(done);
        }
    };
    ...
}
```

**Comment by gorankarlic** [comment]
Thank you for reporting this. It is now resolved and `const client = await Redis.connect(opts);` will now resolve the promise if a connection has been established or reject the promise with the related error  if the connection could not be established.
